---
application:
  name: "saurabh-app"
  project: "CovidDefender"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "database"
  version: "12"
routers:
- name: "main-saurabh-app"
  routes:
  - application_name: "saurabh-app"
    paths:
    - "/*"
